/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jp.ac.uryukyu.ie.e205760;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

/**
 * Todoリストのテストを行うクラス。
 */
class TodoListTest {
    /**
     * TodoリストのTodo削除機能のテスト。
     * TodoListに2つのTodoを追加した後、先頭のTodoを削除。
     * Todoの削除の前後でTodoListの要素数に変化が起きているかを検証する。
     */
    @Test
    void deleteTodoTest() {
        TodoList list = new TodoList();
        Todo one = new Todo("1個目のタスク", 2022, 02, 18, "いっこめ");
        Todo two = new Todo("2個目のタスク", 2022, 02, 19, "にこめ");
        list.addTodo(one);
        list.addTodo(two);
        int before = list.listSize();
        list.deleteTodo(0);
        int after = list.listSize();
        assertNotEquals(before, after);
    }
}
