/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jp.ac.uryukyu.ie.e205760;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class TodoListTest {
    @Test
    void deleteTodoTest() {
        TodoList list = new TodoList();
        Todo one = new Todo("1個目のタスク", 2022, 02, 18, "いっこめ");
        Todo two = new Todo("2個目のタスク", 2022, 02, 19, "にこめ");
        list.addTodo(one);
        list.addTodo(two);
        int before = list.listSize();
        list.deleteTodo(0);
        int after = list.listSize();
        assertNotEquals(before, after);
    }
}
