/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jp.ac.uryukyu.ie.e205760;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class TodoTest {
    @Test
    void deleteTest() {
        //とりあえず通るやつおいとく。
        assertEquals(1, 1);
    }
}
